import os

entries = [
    # docs/hex_ts_study_021.md
    (977, "docs/hex_ts_study_021.md", "hex_ts_study_021_inbound_port_def.png", "./picture/hex_ts_study_021_inbound_port_def.png", "**Theme**: Inbound Port Definition<br><br>**Labels to Render**:<br>- Outside: \"Outside (CLI)\"<br>- Center: \"UseCase\"<br>- Scroll: \"Contract (Port)\"<br>- Bubble: \"OK, in this shape!\"<br><br>**Visual Details**:<br>1. Core Concept: Inbound Port is a contract.<br>2. Metaphor: Outside character asking \"I want to call this!\", Center character (UseCase) holding a scroll (Contract) saying \"OK, pass it in THIS shape!\".<br>3. Action: Agreeing on contract.<br>4. Layout: Interaction between two characters.", "## 2. Inbound Portってなに？（一言で）🗣️🔌"),
    (978, "docs/hex_ts_study_021.md", "hex_ts_study_021_port_essentials.png", "./picture/hex_ts_study_021_port_essentials.png", "**Theme**: Port Essentials<br><br>**Labels to Render**:<br>- Input: \"Input (Mailbox)\"<br>- Output: \"Output (Package)\"<br>- Failure: \"Failure (Alarm)\"<br><br>**Visual Details**:<br>1. Core Concept: The three things defined by the Port.<br>2. Metaphor: Three distinct icons. 1. Input (Mailbox/Post). 2. Output (Out tray/Package). 3. Failure (Alarm/Sign).<br>3. Action: Displaying.<br>4. Layout: Three icons in a row.", "## 3. Inbound Portが決める3点セット 🍱✨"),
    (979, "docs/hex_ts_study_021.md", "hex_ts_study_021_validation_gates.png", "./picture/hex_ts_study_021_validation_gates.png", "**Theme**: Validation Gates<br><br>**Labels to Render**:<br>- Gate 1: \"Adapter (Format Check)\"<br>- Gate 2: \"Domain (Rule Check)\"<br>- Pass: \"Valid\"<br>- Stop: \"Invalid\"<br><br>**Visual Details**:<br>1. Core Concept: Where to check what.<br>2. Metaphor: A security checkpoint. Gate 1 (Adapter) checks for valid ID format. Gate 2 (Domain) checks if the person is on the banned list.<br>3. Action: Checking.<br>4. Layout: Sequential gates.", "## 4. 入口の“入力チェック”はどこでやる？📌😊"),
    (980, "docs/hex_ts_study_021.md", "hex_ts_study_021_todo_ports.png", "./picture/hex_ts_study_021_todo_ports.png", "**Theme**: Todo Ports<br><br>**Labels to Render**:<br>- Port 1: \"AddTodo\"<br>- Port 2: \"CompleteTodo\"<br>- Port 3: \"ListTodos\"<br>- Core: \"UseCase\"<br><br>**Visual Details**:<br>1. Core Concept: One port per use case.<br>2. Metaphor: Three specific sockets or doors labeled \"Add\", \"Complete\", \"List\" leading into the Core.<br>3. Action: Connecting.<br>4. Layout: Three entry points.", "## 5. 今回のミニアプリで作る Inbound Port（3つ）📝✅"),
    (981, "docs/hex_ts_study_021.md", "hex_ts_study_021_port_granularity.png", "./picture/hex_ts_study_021_port_granularity.png", "**Theme**: Port Granularity<br><br>**Labels to Render**:<br>- Good: \"Small Boxes (1 per UseCase)\"<br>- Bad: \"Giant Box (All in One)\"<br>- Comparison: \"Granularity\"<br><br>**Visual Details**:<br>1. Core Concept: Granularity. 1 UseCase = 1 Port vs 1 Big Port.<br>2. Metaphor: A neat stack of small boxes (Good) vs one giant, overflowing box (Bad).<br>3. Action: Comparing.<br>4. Layout: Side by side.", "## 9. Port を “小さく保つ”コツ ✂️✨（増やしすぎ防止）"),
    (982, "docs/hex_ts_study_021.md", "hex_ts_study_021_checklist.png", "./picture/hex_ts_study_021_checklist.png", "**Theme**: Inbound Port Checklist<br><br>**Labels to Render**:<br>- No HTTP: \"No HTTP Request\"<br>- Minimal Input: \"Minimal Input\"<br>- DTO Output: \"DTO Output\"<br>- Promise: \"Promise\"<br><br>**Visual Details**:<br>1. Core Concept: Self-check.<br>2. Metaphor: A clipboard with checks. Items listed are \"No HTTP\", \"Minimal Input\", \"DTO Output\", \"Promise\".<br>3. Action: Checking.<br>4. Layout: Checklist.", "## 12. “良い Inbound Port” チェックリスト ✅🔎✨"),

    # docs/hex_ts_study_022.md
    (983, "docs/hex_ts_study_022.md", "hex_ts_study_022_repo_definition.png", "./picture/hex_ts_study_022_repo_definition.png", "**Theme**: Repository Definition<br><br>**Labels to Render**:<br>- Interface: \"Collection Interface\"<br>- Hidden: \"Database\"<br>- Box: \"Repository\"<br><br>**Visual Details**:<br>1. Core Concept: Repository looks like a collection but hides DB.<br>2. Metaphor: A magical box labeled \"Repository\". It looks like a simple array/collection from the top, but hidden underneath is complex storage (DB).<br>3. Action: Hiding implementation.<br>4. Layout: Cross-section.", "## 2. Repositoryってなに？（超やさしく）🧺💡"),
    (984, "docs/hex_ts_study_022.md", "hex_ts_study_022_outbound_port_reason.png", "./picture/hex_ts_study_022_outbound_port_reason.png", "**Theme**: Outbound Port Reason<br><br>**Labels to Render**:<br>- Core: \"Core\"<br>- Port: \"Port (Window)\"<br>- Implementation: \"DB / File (Hidden)\"<br>- Package: \"Todo\"<br><br>**Visual Details**:<br>1. Core Concept: Center only knows \"I need to save\". Outer layer handles \"How/Where\".<br>2. Metaphor: The Core character handing a package \"Todo\" to a window labeled \"Repository Port\". They don't see if it goes to a warehouse (DB) or a shelf (File) behind the window.<br>3. Action: Handing over.<br>4. Layout: Side view.", "## 3. なんで“Outbound Port”として切るの？🧭🔥"),
    (985, "docs/hex_ts_study_022.md", "hex_ts_study_022_repo_tailoring.png", "./picture/hex_ts_study_022_repo_tailoring.png", "**Theme**: Repo Tailoring<br><br>**Labels to Render**:<br>- UseCase: \"I need Save, Find\"<br>- Port: \"Tailored Port\"<br>- Action: \"Cutting Cloth\"<br><br>**Visual Details**:<br>1. Core Concept: Defining the port based on UseCase needs.<br>2. Metaphor: A UseCase character holding a shopping list of needs. A tailor (Port) is cutting a cloth to fit exactly those needs.<br>3. Action: Tailoring.<br>4. Layout: Interaction.", "## 4. Repository Port の決め方（手順）🪜✨"),
    (986, "docs/hex_ts_study_022.md", "hex_ts_study_022_fat_vs_slim_repo.png", "./picture/hex_ts_study_022_fat_vs_slim_repo.png", "**Theme**: Fat vs Slim Repo<br><br>**Labels to Render**:<br>- Fat: \"Fat Repo (All Tools)\"<br>- Slim: \"Slim Repo (Only Needed)\"<br>- Comparison: \"Efficiency\"<br><br>**Visual Details**:<br>1. Core Concept: Avoid \"Kitchen Sink\" repositories.<br>2. Metaphor: A \"Fat Repository\" monster holding too many tools (SQL, Search, DeleteAll). A \"Slim Repository\" hero holding only 3 tools (Save, Find, List).<br>3. Action: Comparing.<br>4. Layout: Side by side.", "## 5. よくある事故（先に潰す）🚨😇"),
    (987, "docs/hex_ts_study_022.md", "hex_ts_study_022_domain_type_rule.png", "./picture/hex_ts_study_022_domain_type_rule.png", "**Theme**: Domain Type Rule<br><br>**Labels to Render**:<br>- Port: \"Repository Port\"<br>- Allowed: \"Domain Object (Todo)\"<br>- Blocked: \"DB Row / SQL\"<br>- Bouncer: \"Guard\"<br><br>**Visual Details**:<br>1. Core Concept: Repository deals with Domain types, not DB types.<br>2. Metaphor: The Repository Port accepts a \"Todo\" object (Clean). It does NOT accept a \"Row\" object (Dirty). A bouncer stops the Row object.<br>3. Action: Filtering.<br>4. Layout: Gate scene.", "### ポイント1：Repositoryは“ドメイン型”を扱ってOK 🧠💞"),
    (988, "docs/hex_ts_study_022.md", "hex_ts_study_022_usecase_dependency.png", "./picture/hex_ts_study_022_usecase_dependency.png", "**Theme**: UseCase Dependency Inversion<br><br>**Labels to Render**:<br>- UseCase: \"UseCase Logic\"<br>- Port: \"Repository Port (Interface)\"<br>- DB: \"Database (Impl)\"<br>- Arrow: \"Depends On\"<br><br>**Visual Details**:<br>1. Core Concept: UseCase depending on Port.<br>2. Metaphor: UseCase logic block connecting to \"TodoRepositoryPort\" socket. The dependency arrow points to the Port, not the DB.<br>3. Action: Connecting.<br>4. Layout: Dependency diagram.", "## 8. ユースケース側はこうなる（中心がスッキリ😍）🧠✨"),
    (989, "docs/hex_ts_study_022.md", "hex_ts_study_022_checklist.png", "./picture/hex_ts_study_022_checklist.png", "**Theme**: Repository Checklist<br><br>**Labels to Render**:<br>- Naming: \"UseCase Language\"<br>- Size: \"Minimal\"<br>- Type: \"No DB Types\"<br>- Async: \"Promise\"<br><br>**Visual Details**:<br>1. Core Concept: Self-check.<br>2. Metaphor: A clipboard with checks. Items: \"UseCase Language\", \"Minimal\", \"No DB Types\", \"Promise\".<br>3. Action: Checking.<br>4. Layout: Checklist.", "## 9. “良いRepository Port”チェックリスト ✅🔎✨"),

    # docs/hex_ts_study_023.md
    (990, "docs/hex_ts_study_023.md", "hex_ts_study_023_sweep_dependencies.png", "./picture/hex_ts_study_023_sweep_dependencies.png", "**Theme**: Sweep Dependencies<br><br>**Labels to Render**:<br>- Core: \"Core Room\"<br>- Sweep: \"Remove\"<br>- Trash: \"Clock / Random\"<br><br>**Visual Details**:<br>1. Core Concept: Moving small dependencies like Clock/UUID out of the core.<br>2. Metaphor: A Core character sweeping \"Clock\" and \"Dice\" (Random) out of the room labeled \"Core\".<br>3. Action: Sweeping.<br>4. Layout: Room cleaning.", "## 1) この章のゴール 🎯💖"),
    (991, "docs/hex_ts_study_023.md", "hex_ts_study_023_moving_target.png", "./picture/hex_ts_study_023_moving_target.png", "**Theme**: Moving Target<br><br>**Labels to Render**:<br>- Tester: \"Tester\"<br>- Target 1: \"Time (Moving)\"<br>- Target 2: \"UUID (Changing)\"<br>- Emotion: \"Dizzy\"<br><br>**Visual Details**:<br>1. Core Concept: Test instability due to changing time/randomness.<br>2. Metaphor: A tester trying to measure a moving target. The \"Time\" is a clock running wild. The \"UUID\" is changing shape constantly.<br>3. Action: Trying to measure.<br>4. Layout: Chaotic scene.", "## 2) 「小さな依存」って何がダメなの？😵‍💫💥"),
    (992, "docs/hex_ts_study_023.md", "hex_ts_study_023_small_ports.png", "./picture/hex_ts_study_023_small_ports.png", "**Theme**: Small Ports<br><br>**Labels to Render**:<br>- Wall: \"Core Wall\"<br>- Socket 1: \"ClockPort\"<br>- Socket 2: \"IdGeneratorPort\"<br><br>**Visual Details**:<br>1. Core Concept: Defining interfaces for Time and ID.<br>2. Metaphor: Two sockets on the wall of the Core. One labeled \"ClockPort\", one labeled \"IdGeneratorPort\".<br>3. Action: Installing sockets.<br>4. Layout: Wall close-up.", "## 4) 実装：Port を作る（中心側）🧠🔌"),
    (993, "docs/hex_ts_study_023.md", "hex_ts_study_023_small_adapters.png", "./picture/hex_ts_study_023_small_adapters.png", "**Theme**: Small Adapters<br><br>**Labels to Render**:<br>- Plug 1: \"SystemClock\"<br>- Plug 2: \"CryptoId\"<br>- Socket: \"Port\"<br><br>**Visual Details**:<br>1. Core Concept: Adapters implementing the ports.<br>2. Metaphor: A \"Real World\" plug connecting to the \"ClockPort\". A \"Crypto\" plug connecting to the \"IdGeneratorPort\".<br>3. Action: Plugging in.<br>4. Layout: Connection.", "## 5) Adapter を作る（外側）🧩🚀"),
    (994, "docs/hex_ts_study_023.md", "hex_ts_study_023_ingredient_delivery.png", "./picture/hex_ts_study_023_ingredient_delivery.png", "**Theme**: Ingredient Delivery<br><br>**Labels to Render**:<br>- Chef: \"UseCase\"<br>- Courier: \"Adapter\"<br>- Item 1: \"Time\"<br>- Item 2: \"ID\"<br><br>**Visual Details**:<br>1. Core Concept: UseCase receiving Date/ID as values.<br>2. Metaphor: A chef (UseCase) receiving fresh ingredients (Time, ID) from a delivery person (Adapter), instead of growing them in the kitchen.<br>3. Action: Delivering.<br>4. Layout: Kitchen scene.", "## 6) ユースケースで使う（中心は外側を知らない）🧠🛡️"),
    (995, "docs/hex_ts_study_023.md", "hex_ts_study_023_fake_control.png", "./picture/hex_ts_study_023_fake_control.png", "**Theme**: Fake Control<br><br>**Labels to Render**:<br>- Hand: \"Test Control\"<br>- Clock: \"Fixed Time\"<br>- ID: \"Fixed ID\"<br>- Status: \"Stable\"<br><br>**Visual Details**:<br>1. Core Concept: Controlling time/ID in tests.<br>2. Metaphor: A \"God Mode\" hand stopping the clock and setting it to a specific time. A stamp creating fixed IDs \"ID-001\".<br>3. Action: Controlling.<br>4. Layout: Top-down control.", "## 7) テストがラクになる（ここがご褒美）🧪🍰✨"),
    (996, "docs/hex_ts_study_023.md", "hex_ts_study_023_anti_patterns.png", "./picture/hex_ts_study_023_anti_patterns.png", "**Theme**: Dependency Anti-Patterns<br><br>**Labels to Render**:<br>- Bad 1: \"Direct Call (Bypass)\"<br>- Bad 2: \"Giant Utils Port\"<br>- Result: \"Messy\"<br><br>**Visual Details**:<br>1. Core Concept: Direct calls vs Giant Utils Port.<br>2. Metaphor: 1. A wire bypassing the port and going straight to a \"Clock\" (Direct call). 2. A giant bloated plug labeled \"Utils\" trying to fit into a tiny socket.<br>3. Action: Failing to connect properly.<br>4. Layout: Side by side bad examples.", "## 10) アンチパターン警報 🚨😱"),

    # docs/hex_ts_study_024.md
    (997, "docs/hex_ts_study_024.md", "hex_ts_study_024_cli_success.png", "./picture/hex_ts_study_024_cli_success.png", "**Theme**: CLI Success<br><br>**Labels to Render**:<br>- Terminal: \"PowerShell\"<br>- Command: \"npm run cli -- add\"<br>- Output: \"Success!\"<br>- Emotion: \"Happy\"<br><br>**Visual Details**:<br>1. Core Concept: Successful execution of CLI.<br>2. Metaphor: A terminal window showing the successful execution of `add`, `list`, `done`. A green checkmark or confetti.<br>3. Action: Running command.<br>4. Layout: Terminal view.", "## 1) 今日の完成イメージ🎯✨"),
    (998, "docs/hex_ts_study_024.md", "hex_ts_study_024_thin_adapter_layers.png", "./picture/hex_ts_study_024_thin_adapter_layers.png", "**Theme**: Thin Adapter Layers<br><br>**Labels to Render**:<br>- Layer 1: \"Parse\"<br>- Layer 2: \"Validate\"<br>- Layer 3: \"Call\"<br>- Layer 4: \"Present\"<br>- No Fat: \"No Business Logic\"<br><br>**Visual Details**:<br>1. Core Concept: The Adapter should be thin (Parse -> Validate -> Call -> Present).<br>2. Metaphor: A thin slice of cake or a diet plan. It has 4 distinct layers: Parse, Validate, Call, Present. No \"Business Rule\" fat layer.<br>3. Action: Displaying layers.<br>4. Layout: Stacked layers.", "ポイントはこれ👇"),
    (999, "docs/hex_ts_study_024.md", "hex_ts_study_024_adapter_di.png", "./picture/hex_ts_study_024_adapter_di.png", "**Theme**: Adapter DI<br><br>**Labels to Render**:<br>- Adapter: \"CliAdapter\"<br>- Input: \"UseCase (Function)\"<br>- Action: \"Inject\"<br><br>**Visual Details**:<br>1. Core Concept: Adapter receives UseCases as arguments/functions.<br>2. Metaphor: A socket (Adapter) waiting for a plug (UseCase). The plug is handed to it, not created inside.<br>3. Action: Injecting.<br>4. Layout: Connection.", "### 5-1. まずはユースケースを“関数”として受け取る🔌✨"),
    (1000, "docs/hex_ts_study_024.md", "hex_ts_study_024_main_assembly.png", "./picture/hex_ts_study_024_main_assembly.png", "**Theme**: Main Assembly<br><br>**Labels to Render**:<br>- Main: \"main.ts\"<br>- Part A: \"CliAdapter\"<br>- Part B: \"UseCase\"<br>- Action: \"Connect\"<br><br>**Visual Details**:<br>1. Core Concept: main.ts assembling the parts.<br>2. Metaphor: A builder (Main) connecting the CLI Adapter block to the UseCase block.<br>3. Action: Assembling.<br>4. Layout: Construction.", "## 6) main.ts：とりあえず動かす簡易組み立て🧩🏗️"),
    (1001, "docs/hex_ts_study_024.md", "hex_ts_study_024_npm_trap.png", "./picture/hex_ts_study_024_npm_trap.png", "**Theme**: NPM Run Trap<br><br>**Labels to Render**:<br>- Trap: \"npm run cli add (Fail)\"<br>- Bridge: \"npm run cli -- add (Success)\"<br>- Character: \"User\"<br><br>**Visual Details**:<br>1. Core Concept: Forgetting the `--`.<br>2. Metaphor: A trap. `npm run cli add` falls into a pit. `npm run cli -- add` bridges the gap safely.<br>3. Action: Crossing safely.<br>4. Layout: Trap vs Bridge.", "### ✅ npm の -- を忘れる"),
    (1002, "docs/hex_ts_study_024.md", "hex_ts_study_024_adapter_check.png", "./picture/hex_ts_study_024_adapter_check.png", "**Theme**: Adapter Check<br><br>**Labels to Render**:<br>- Adapter: \"Adapter Code\"<br>- Inspector: \"Magnifying Glass\"<br>- Search: \"No Domain Logic\"<br><br>**Visual Details**:<br>1. Core Concept: Checking if the adapter is truly thin.<br>2. Metaphor: A magnifying glass inspecting the code for \"Domain Imports\" or \"Business Logic\".<br>3. Action: Inspecting.<br>4. Layout: Zoom in.", "## 10) “薄いAdapter”セルフチェック✅🥗"),

    # docs/hex_ts_study_025.md
    (1003, "docs/hex_ts_study_025.md", "hex_ts_study_025_adapter_translation.png", "./picture/hex_ts_study_025_adapter_translation.png", "**Theme**: Adapter Translation<br><br>**Labels to Render**:<br>- Input: \"Messy CLI Args\"<br>- Booth: \"Translator (Adapter)\"<br>- Output: \"Clean DTO\"<br><br>**Visual Details**:<br>1. Core Concept: CLI input is \"messy\", UseCase input (DTO) must be \"clean\".<br>2. Metaphor: A translator booth. Messy, loud, incoherent speech (CLI Args) enters one side. Clean, polite, structured notes (DTO) come out the other.<br>3. Action: Translating.<br>4. Layout: Left to Right.", "## 2. なぜ「CLI入力→DTO変換」を Adapter に置くの？🧩"),
    (1004, "docs/hex_ts_study_025.md", "hex_ts_study_025_parse_args.png", "./picture/hex_ts_study_025_parse_args.png", "**Theme**: ParseArgs Machine<br><br>**Labels to Render**:<br>- Input: \"--title foo\"<br>- Machine: \"util.parseArgs\"<br>- Bins: \"values / positionals\"<br><br>**Visual Details**:<br>1. Core Concept: Node's `util.parseArgs` organizing raw arguments.<br>2. Metaphor: A sorting machine. Raw arguments (`--title`, `\"foo\"`) fall in. The machine sorts them into named bins (`values.title`).<br>3. Action: Sorting.<br>4. Layout: Machine view.", "## 4. パースの道具：Node標準 parseArgs を使う 🔧✨"),
    (1005, "docs/hex_ts_study_025.md", "hex_ts_study_025_dto_location.png", "./picture/hex_ts_study_025_dto_location.png", "**Theme**: DTO Location Map<br><br>**Labels to Render**:<br>- Layer: \"App Layer\"<br>- Box: \"DTO Mailbox\"<br>- Sender: \"Adapter\"<br><br>**Visual Details**:<br>1. Core Concept: DTOs live in the App layer.<br>2. Metaphor: A map of the architecture. The \"App\" layer has a mailbox labeled \"DTOs\". The \"Adapter\" layer puts letters into it.<br>3. Action: Delivering.<br>4. Layout: Map view.", "## 5. DTOってどこに置く？（置き場所のおすすめ）📁🧭"),
    (1006, "docs/hex_ts_study_025.md", "hex_ts_study_025_zod_validation.png", "./picture/hex_ts_study_025_zod_validation.png", "**Theme**: Zod Validation<br><br>**Labels to Render**:<br>- Input: \"Data\"<br>- Mold: \"Zod Schema\"<br>- Pass: \"Valid\"<br>- Reject: \"Invalid\"<br><br>**Visual Details**:<br>1. Core Concept: Zod checking the shape of data at the entry.<br>2. Metaphor: A mold or template. The input data is pressed against the Zod mold. If it fits, it passes. If not, it's rejected.<br>3. Action: Molding.<br>4. Layout: Process flow.", "### 6-2. バリデーション：Zod で「入口チェック」する 🧪✨"),
    (1007, "docs/hex_ts_study_025.md", "hex_ts_study_025_command_switch.png", "./picture/hex_ts_study_025_command_switch.png", "**Theme**: Command Switch<br><br>**Labels to Render**:<br>- Train: \"Command\"<br>- Switch: \"Arg[0]\"<br>- Tracks: \"Add / Complete / List\"<br><br>**Visual Details**:<br>1. Core Concept: Sub-command switching (add vs complete vs list).<br>2. Metaphor: A railway switch or decision tree. The train (CLI Command) takes the \"Add\" track, \"Complete\" track, or \"List\" track based on the first argument.<br>3. Action: Switching.<br>4. Layout: Branching.", "### 6-3. コマンドをパースする（parseArgs）🔍⌨️"),
    (1008, "docs/hex_ts_study_025.md", "hex_ts_study_025_quote_trap.png", "./picture/hex_ts_study_025_quote_trap.png", "**Theme**: Quote Trap<br><br>**Labels to Render**:<br>- Safe: \"'Buy Milk' (Together)\"<br>- Broken: \"Buy Milk (Split)\"<br>- Cause: \"Missing Quotes\"<br><br>**Visual Details**:<br>1. Core Concept: Arguments breaking without quotes.<br>2. Metaphor: A string `\"Buy Milk\"` staying together inside a bubble. A string `Buy Milk` breaking into two pieces `Buy` and `Milk` when it hits the CLI wall.<br>3. Action: Breaking.<br>4. Layout: Comparison.", "### 7-1. ダブルクォート忘れ問題 \"...\" 😇"),
    (1009, "docs/hex_ts_study_025.md", "hex_ts_study_025_fat_adapter_check.png", "./picture/hex_ts_study_025_fat_adapter_check.png", "**Theme**: Fat Adapter Check<br><br>**Labels to Render**:<br>- Adapter: \"Adapter\"<br>- Hat: \"Core Hat (Business Rules)\"<br>- Status: \"Overloaded\"<br><br>**Visual Details**:<br>1. Core Concept: Adapter doing too much (Business Logic).<br>2. Metaphor: An Adapter character trying to do the \"Core's Job\" (wearing a Core hat) and looking silly/overloaded.<br>3. Action: Wearing wrong hat.<br>4. Layout: Character focus.", "## 8. 「Adapterが太ってない？」チェック🥗⚠️"),

    # docs/hex_ts_study_026.md
    (1010, "docs/hex_ts_study_026.md", "hex_ts_study_026_inmemory_joy.png", "./picture/hex_ts_study_026_inmemory_joy.png", "**Theme**: InMemory Joy<br><br>**Labels to Render**:<br>- Rocket: \"Speed\"<br>- Bubble: \"Disposable\"<br>- Emotion: \"Joy\"<br><br>**Visual Details**:<br>1. Core Concept: InMemory speed and disposability.<br>2. Metaphor: A rocket (Test speed) and a soap bubble (Disappearing data). The bubble pops when the app stops.<br>3. Action: Floating.<br>4. Layout: Rocket and Bubble.", "## 2) InMemoryRepositoryって何がうれしいの？ 🥰"),
    (1011, "docs/hex_ts_study_026.md", "hex_ts_study_026_folder_structure.png", "./picture/hex_ts_study_026_folder_structure.png", "**Theme**: Folder Structure<br><br>**Labels to Render**:<br>- Tree: \"src\"<br>- Branch: \"adapters/outbound\"<br>- Leaf: \"InMemory...\"<br><br>**Visual Details**:<br>1. Core Concept: Organization of the new adapter.<br>2. Metaphor: A folder tree. Highlighting `src/adapters/outbound/InMemory...`.<br>3. Action: Highlighting.<br>4. Layout: Tree view.", "## 3) 置き場所（迷子防止）📁🧭"),
    (1012, "docs/hex_ts_study_026.md", "hex_ts_study_026_snapshot_copy.png", "./picture/hex_ts_study_026_snapshot_copy.png", "**Theme**: Snapshot Copy<br><br>**Labels to Render**:<br>- Original: \"Domain Object\"<br>- Copier: \"Snapshot\"<br>- Archive: \"Map Store\"<br><br>**Visual Details**:<br>1. Core Concept: Storing Snapshot, not Domain Object (reference safety).<br>2. Metaphor: A photocopier. The Domain Object (Original) is copied into a Snapshot (Photo) before being put in the Map (Archive).<br>3. Action: Copying.<br>4. Layout: Process flow.", "### 5-3) InMemory Adapter（本命）🧩✨"),
    (1013, "docs/hex_ts_study_026.md", "hex_ts_study_026_usecase_blindfold.png", "./picture/hex_ts_study_026_usecase_blindfold.png", "**Theme**: UseCase Blindfold<br><br>**Labels to Render**:<br>- Character: \"UseCase\"<br>- Blindfold: \"Interface\"<br>- Hand: \"Repository\"<br><br>**Visual Details**:<br>1. Core Concept: UseCase doesn't know it's InMemory.<br>2. Metaphor: UseCase wearing a blindfold, handing a package to \"Repository\". It feels the same whether it's an InMemory hand or a DB hand taking it.<br>3. Action: Handing over.<br>4. Layout: Interaction.", "## 6) 差し替え体験：UseCaseは何も知らない 🙅‍♀️✨"),
    (1014, "docs/hex_ts_study_026.md", "hex_ts_study_026_composition_root.png", "./picture/hex_ts_study_026_composition_root.png", "**Theme**: Composition Root Assembly<br><br>**Labels to Render**:<br>- Builder: \"Main\"<br>- Block A: \"InMemoryRepo\"<br>- Block B: \"UseCase\"<br><br>**Visual Details**:<br>1. Core Concept: Assembling the parts.<br>2. Metaphor: A builder (Main) connecting the \"InMemoryRepo\" block to the \"AddTodoUseCase\" block.<br>3. Action: Connecting.<br>4. Layout: Assembly.", "## 7) Composition Rootで組み立てる 🧩🏗️"),
    (1015, "docs/hex_ts_study_026.md", "hex_ts_study_026_test_speed.png", "./picture/hex_ts_study_026_test_speed.png", "**Theme**: Test Speed<br><br>**Labels to Render**:<br>- Stopwatch: \"0.01s\"<br>- Runner: \"Test\"<br>- Speed: \"Supersonic\"<br><br>**Visual Details**:<br>1. Core Concept: Fast tests because of InMemory.<br>2. Metaphor: A stopwatch showing \"0.01s\". A runner breaking the sound barrier.<br>3. Action: Running fast.<br>4. Layout: Speed.", "## 8) テストが一気に楽になるよ🧪⚡（Vitest例）"),
    (1016, "docs/hex_ts_study_026.md", "hex_ts_study_026_thin_waiter.png", "./picture/hex_ts_study_026_thin_waiter.png", "**Theme**: Thin Waiter<br><br>**Labels to Render**:<br>- Waiter: \"Adapter\"<br>- Tray: \"Data\"<br>- No Cooking: \"No Logic\"<br><br>**Visual Details**:<br>1. Core Concept: Adapter doing only I/O work.<br>2. Metaphor: A thin waiter carrying a tray (Data). Not cooking (Logic), not eating (Consuming). Just carrying.<br>3. Action: Carrying.<br>4. Layout: Character focus.", "## 9) “Adapterが薄いか”セルフチェック 🥗✅"),

    # docs/hex_ts_study_027.md
    (1017, "docs/hex_ts_study_027.md", "hex_ts_study_027_file_persistence.png", "./picture/hex_ts_study_027_file_persistence.png", "**Theme**: File Persistence Ninja<br><br>**Labels to Render**:<br>- Core: \"Core (Sleeping)\"<br>- Ninja: \"File Adapter\"<br>- Scroll: \"todos.json\"<br><br>**Visual Details**:<br>1. Core Concept: Saving data to a file without touching the Core.<br>2. Metaphor: A Core character sleeping peacefully while a \"File Adapter\" ninja silently writes data to a scroll (File) in the background.<br>3. Action: Sneaky writing.<br>4. Layout: Background action.", "## 1) 今日のゴール 🎯✨"),
    (1018, "docs/hex_ts_study_027.md", "hex_ts_study_027_port_adapter_role.png", "./picture/hex_ts_study_027_port_adapter_role.png", "**Theme**: Port vs Adapter Role<br><br>**Labels to Render**:<br>- Contract: \"Port\"<br>- Worker: \"Adapter\"<br>- Whistle: \"Referee (Rules)\"<br><br>**Visual Details**:<br>1. Core Concept: Port is the contract, Adapter is the implementation.<br>2. Metaphor: A clear contract scroll (Port). A worker (Adapter) executing the contract strictly. If the worker starts making up new rules, a referee blows a whistle.<br>3. Action: Working/Whistling.<br>4. Layout: Work scene.", "## 2) まず大事な考え方（超短く）🛡️🔌🧩"),
    (1019, "docs/hex_ts_study_027.md", "hex_ts_study_027_record_format.png", "./picture/hex_ts_study_027_record_format.png", "**Theme**: Record Format Flattening<br><br>**Labels to Render**:<br>- Object: \"Domain Object (3D)\"<br>- Flat: \"Record (2D)\"<br>- File: \"File Folder\"<br><br>**Visual Details**:<br>1. Core Concept: Converting Domain Object to a Record format for storage.<br>2. Metaphor: A complex Domain Object (3D shape) being flattened into a 2D drawing (Record) to fit into a file folder.<br>3. Action: Flattening.<br>4. Layout: Transformation.", "## 3) 保存形式を決める（シンプルが最強）📄✨"),
    (1020, "docs/hex_ts_study_027.md", "hex_ts_study_027_safe_write.png", "./picture/hex_ts_study_027_safe_write.png", "**Theme**: Safe Write<br><br>**Labels to Render**:<br>- Bridge 1: \"Old File\"<br>- Bridge 2: \"Temp File (Building)\"<br>- Action: \"Switch (Rename)\"<br><br>**Visual Details**:<br>1. Core Concept: Writing to a temp file and then renaming to ensure atomicity.<br>2. Metaphor: A construction worker building a new bridge (Temp) next to the old one. Only when the new one is perfect do they switch the traffic signs (Rename).<br>3. Action: Switching.<br>4. Layout: Bridge construction.", "#### ここ、めっちゃ大事ポイントだよ〜📌✨"),
    (1021, "docs/hex_ts_study_027.md", "hex_ts_study_027_write_queue.png", "./picture/hex_ts_study_027_write_queue.png", "**Theme**: Write Queue<br><br>**Labels to Render**:<br>- Queue: \"Write Queue\"<br>- Bouncer: \"Guard\"<br>- Door: \"File Access\"<br><br>**Visual Details**:<br>1. Core Concept: Serializing writes to prevent race conditions.<br>2. Metaphor: A single-file line of data packets waiting to enter a door (File). A bouncer ensures only one enters at a time.<br>3. Action: Queuing.<br>4. Layout: Lineup.", "### 4-2) FileRepository 本体（JSON読み書き＋安全対策）📄💾🧩"),
    (1022, "docs/hex_ts_study_027.md", "hex_ts_study_027_repo_swap.png", "./picture/hex_ts_study_027_repo_swap.png", "**Theme**: Repository Swap<br><br>**Labels to Render**:<br>- Board: \"Main Plug Board\"<br>- Plug 1: \"InMemory\"<br>- Plug 2: \"File\"<br>- Action: \"Swap\"<br><br>**Visual Details**:<br>1. Core Concept: Swapping InMemory for FileRepo in Main.<br>2. Metaphor: A plug board (Main). Unplugging the \"InMemory\" plug and plugging in the \"File\" plug. The rest of the machine (App) stays running.<br>3. Action: Swapping.<br>4. Layout: Plug board.", "## 5) Composition Root で差し替える 🧩🏗️✨"),
    (1023, "docs/hex_ts_study_027.md", "hex_ts_study_027_fat_check.png", "./picture/hex_ts_study_027_fat_check.png", "**Theme**: Fat Adapter Check 2<br><br>**Labels to Render**:<br>- Fat: \"Bloated Adapter\"<br>- Thin: \"Fit Adapter\"<br>- Diet: \"Remove Logic\"<br><br>**Visual Details**:<br>1. Core Concept: Adapter doing too much.<br>2. Metaphor: A \"File Adapter\" looking bloated because it ate \"Business Rules\". A \"Thin Adapter\" looking fit.<br>3. Action: Comparing.<br>4. Layout: Side by side.", "## 7) Adapter が “太ってない？”チェック 🥗⚠️✅"),
]

with open("docs/picture/image_generation_plan.md", "a", encoding="utf-8") as f:
    for entry in entries:
        row = f"| {entry[0]} | {entry[1]} | {entry[2]} | {entry[3]} | {entry[4]} | {entry[5]} |\n"
        f.write(row)
